@startuml Suivi des résultats des apprenants

title diagramme de sequence - Suivi des résultats des apprenants

actor Formateur as formateur
participant "U I" as ui
participant "Serveur / API" as serveur
participant DB as db

autonumber

@enduml