@startuml Modifier une évaluation

title diagramme de sequence - Modifier une évaluation

actor Formateur as formateur
participant "U I" as ui
participant "Serveur / API" as serveur
participant DB as db

autonumber

@enduml