@startuml Suppression de cours

title diagramme de sequence - Supression de cours

actor Formateur as formateur
participant "U I" as ui
participant "Serveur / API" as serveur
participant DB as db

autonumber

@enduml